name: GitHub Actions Demo
on:
  push:
    paths:
      - './ui/**'
  pull_request:
    paths:
      - './ui/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.16.2"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"
      - name: Build Static file
        run: |
          set -exu
          cd ./ui
          npm install
          npm run build
          cd ./build
          go install github.com/mjibson/esc
          export PATH=$PATH:$(go env GOPATH)/bin
          #
          esc -o ../../static.go -pkg=main -modtime=0 -prefix=/ ./
          git status
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Add generated files'
          add: '*'
