name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/github.com/${{ github.repository }}
      - uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.16.2"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"
      - name: Build Static file
        run: |
          set -exu
          cd "${GITHUB_WORKSPACE}"/src/github.com/${{ github.repository }}/ui
          npm i
          npm run build
          cd ./build
          go get -u github.com/mjibson/esc
          go install github.com/mjibson/esc
          export PATH=$PATH:$(go env GOPATH)/bin
          esc -o ../../static.go -pkg=main -modtime=0 -prefix=/ ./
          git status
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Add generated files'
          add: '*'
          cwd: '${{ GITHUB_WORKSPACE }}/src/github.com/${{ github.repository }}'